#FROM python:3.13-slim

#WORKDIR /app

#ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
#ENV UV_COMPILE_BYTECODE=1

#COPY pyproject.toml .
#COPY uv.lock .
#RUN pip install --no-cache-dir uv
#RUN uv sync --frozen --no-install-project --no-dev

#COPY src/agents/ ./agents/
#COPY src/core/ ./core/
#COPY src/memory/ ./memory/
#COPY src/schema/ ./schema/
#COPY src/service/ ./service/
#COPY src/vector_databases/ ./vector_databases/
#COPY src/run_service.py .

#CMD ["python", "run_service.py"]



FROM python:3.13-slim

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
ENV UV_COMPILE_BYTECODE=1

# ← add build deps for psycopg2
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
 && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml .
COPY uv.lock .
RUN pip install --no-cache-dir uv
RUN uv sync --frozen --no-install-project --no-dev

COPY src/agents/ ./agents/
COPY src/core/ ./core/
COPY src/memory/ ./memory/
COPY src/schema/ ./schema/
COPY src/service/ ./service/
COPY src/vector_databases/ ./vector_databases/
COPY src/run_service.py .

CMD ["python", "run_service.py"]
